### ISSUE TITLE
IR remote codes different for LC03

### ISSUE THREAD

**Issue by alexschwantes** [mertenats/Arilux_AL-LC0X#15]
I have the LC03 from Banggood but my IR codes were different to what you had in the code. I changed mine in Arilux.h to:

#ifdef IR_REMOTE
#define ARILUX_IR_CODE_KEY_UP           0xE5CFBD7F
#define ARILUX_IR_CODE_KEY_DOWN         0xA23C94BF
#define ARILUX_IR_CODE_KEY_OFF          0xE721C0DB
#define ARILUX_IR_CODE_KEY_ON           0xF0C41643
#define ARILUX_IR_CODE_KEY_R            0x97483BFB
#define ARILUX_IR_CODE_KEY_G            0x86B0E697
#define ARILUX_IR_CODE_KEY_B            0x9EF4941F
#define ARILUX_IR_CODE_KEY_W            0xA3C8EDDB
#define ARILUX_IR_CODE_KEY_1            0x5BE75E7F
#define ARILUX_IR_CODE_KEY_2            0xF377C5B7
#define ARILUX_IR_CODE_KEY_3            0xC101E57B
#define ARILUX_IR_CODE_KEY_FLASH        0x7EC31EF7
#define ARILUX_IR_CODE_KEY_4            0xD7E84B1B
#define ARILUX_IR_CODE_KEY_5            0xEE4ECCFB
#define ARILUX_IR_CODE_KEY_6            0x51E43D1B
#define ARILUX_IR_CODE_KEY_STROBE       0xFA3F159F
#define ARILUX_IR_CODE_KEY_7            0x2A89195F
#define ARILUX_IR_CODE_KEY_8            0xF63C8657
#define ARILUX_IR_CODE_KEY_9            0x44C407DB
#define ARILUX_IR_CODE_KEY_FADE         0xDC0197DB
#define ARILUX_IR_CODE_KEY_10           0x488F3CBB
#define ARILUX_IR_CODE_KEY_11           0x13549BDF
#define ARILUX_IR_CODE_KEY_12           0x35A9425F
#define ARILUX_IR_CODE_KEY_SMOOTH       0x9716BE3F
#endif

**Comment by SamZorSec** [comment]
It's possible that they are using now a different IR remote.
