### ISSUE TITLE
on compile IRrecv error

### ISSUE THREAD

**Issue by ssolmaz** [mertenats/Arilux_AL-LC0X#25]
hi, 
I installed IRremoteESP8266.h
on compile I am getting the following 

```
Arduino: 1.6.12 (Windows 7), Board: "Generic ESP8266 Module, 80 MHz, 40MHz, DIO, 115200, 1M (64K SPIFFS), ck, Serial, None"

Arilux_AL-LC0X:82: error: 'IRrecv' does not name a type

 IRrecv            irRecv(ARILUX_IR_PIN);

 ^

C:\Users\SSS\Desktop\Arilux_AL-LC0X\Arilux_AL-LC0X.ino: In function 'void handleIRRemote()':

Arilux_AL-LC0X:590: error: 'decode_results' was not declared in this scope

   decode_results  results;

   ^

Arilux_AL-LC0X:590: error: expected ';' before 'results'

   decode_results  results;

                   ^

Arilux_AL-LC0X:592: error: 'irRecv' was not declared in this scope

   if (irRecv.decode(&results)) {

       ^

Arilux_AL-LC0X:592: error: 'results' was not declared in this scope

   if (irRecv.decode(&results)) {

                      ^

C:\Users\SSS\Desktop\Arilux_AL-LC0X\Arilux_AL-LC0X.ino: In function 'void setup()':

Arilux_AL-LC0X:908: error: 'irRecv' was not declared in this scope

   irRecv.enableIRIn();

   ^

exit status 1
'IRrecv' does not name a type
```

**Comment by SamZorSec** [comment]
Have you installed the [IRremoteESP8266](https://github.com/markszabo/IRremoteESP8266) library?

**Comment by SamZorSec** [comment]
Or it's possible that you need to download an older version of the library. 
https://github.com/markszabo/IRremoteESP8266/archive/v1.2.0.zip

**Comment by ssolmaz** [comment]
Thanks for help.
I installed this library (v.1.2.0) and it loaded without error.
But LC04 is unresponsive. It does not take ip.
I think I'm doing something wrong.

**Comment by SamZorSec** [comment]
Your device isn't responsive with the IR remote or with Home Assistant / MQTT? Maybe the IR codes are different.

**Comment by ssolmaz** [comment]
Same as you use (LC04). Does not respond to the remote control. I uploaded it using the second method you described. I will find another FTDI and upload it again in the first method.

**Comment by ssolmaz** [comment]
my LC04 board ESP-IR-A v1.4. Does it matter?

**Comment by SamZorSec** [comment]
Is it working if you're controlling your device with Home Assistant/MQTT? Probably that the IR code are different...
