### ISSUE TITLE
New controller version not working

### ISSUE THREAD

**Issue by ghost** [mertenats/Arilux_AL-LC0X#27]
It appears there are new versions of the LC-01 and LC-02 boards, coming without the metal shield on top of the wifi module.
This firmware doesn't boot on the new version, here is the serial log:

` ets Jan  8 2013,rst cause:1, boot mode:(3,2)                                                                       
                                                                                                                    
load 0x4010f000, len 1384, room 16                                                                                  
tail 8                                                                                                              
chksum 0xef                                                                                                         
csum 0xef                                                                                                           
csum err                                                                                                            
ets_main.c q   `

Looking at the serial boot log before and after the flash, I think these are booting in the wrong mode for some reason: 

Original firmware:  ets Jan  8 2013,rst cause:1, boot mode:(3,7)
After flashing:  ets Jan  8 2013,rst cause:1, boot mode:(3,2)  

Here you can find some info on boot modes:
https://github.com/digistump/OakCore/issues/45

MTD0 GPIO0 GPIO2 Mode
0    0     0     Remapping
0    0     1     UART boot
0    1     0     Jump boot
0    1     1     Flash boot
1    0     0     SDIO LowSpeed V2 IO
1    0     1     SDIO HighSpeed V1 IO
1    1     0     SDIO LowSpeed V1 IO
1    1     1     SDIO HighSpeed V2 IO

A related discussion:
https://community.smartthings.com/t/release-smartlife-h801-rgbw-led-strip-wifi-controller-bulb/51182/1253

**Comment by mariusrugan** [comment]
@thenexor see #27
