### ISSUE TITLE
Arilux LC-01 flash wired DOUT mode

### ISSUE THREAD

**Issue by naxxfish** [mertenats/Arilux_AL-LC0X#28]
After getting my hands on an [LC-01](https://www.banggood.com/ARILUX-AL-LC01-Super-Mini-LED-WIFI-Smart-RGB-Controller-For-RGB-LED-Strip-Light-DC-9-12V-p-1058603.html?rmmds=myorder) from Banggood.com , I attempted to reflash with this firmware following the instructures in the README.md here.  

Unfortunately, it seems that on this particular model the low-cost ESP8266 module is used, in which the PN25F08B flash chip is wired in DOUT mode, not DIO mode as referred to in the readme.  

Here's some reference to a similar problem with a different branded LED controller
https://www.letscontrolit.com/forum/viewtopic.php?t=3071

**Comment by mariusrugan** [comment]
confirming, 
as per #27 also. I have board version V1.4

**Comment by SamZorSec** [comment]
Hi @mariusrugan,
If you're using DOUT mode, can you flash the firmware? Or it's not working?
 
Thanks,
Sam

**Comment by fmaule** [comment]
I'm also confirming. 
Received LC-01 from Banggood (product ID 1058603), couldn't boot when flashing in DIO mode (bootloader csum err)
It's booting just fine when flashed in DOUT mode.

Thanks for the great firmware!

**Comment by mariusrugan** [comment]
Hi Sam,

yes i can, 
using DOUT mode you can flash the firmware. 

First, i thought that shorting GPIO0 (connect with ground) wasn't working at all (i was using tweezers), i couldn't get it in flash mode, code wasn't uploading. 

i can photograph the board (both sides) and you can put it in the readme.

**Comment by SamZorSec** [comment]
Thanks! I'll add a notice in the README file.

Sam
