### ISSUE TITLE
Open box

### ISSUE THREAD

**Issue by HydrelioxGitHub** [mertenats/Arilux_AL-LC0X#31]
Juste a simple question that I think most of them will laugh at it ... Is there a particular way to open the enclosure of the AL-LC03 ? (Youtube video welcomed 😃 )

Thank you for your work !

**Comment by SamZorSec** [comment]
Hi @HydrelioxGitHub,
I did just with a simple cutter.

Sam

**Comment by HydrelioxGitHub** [comment]
Thanks. I opened it with my smaller screwdriver.
