### ISSUE TITLE
[Help] AL-LC01 flashing problems

### ISSUE THREAD

**Issue by papaiatis** [mertenats/Arilux_AL-LC0X#33]
Hi all,

Not sure what I'm doing wrong but I can't flash this firmware on my LC01 v1.4
1. I soldered three wires on the back: RX, TX and GND.
2. I connected the RX (Arilux) to TX (FTDI), TX (Arilux) to RX (FTDI) and GND (Arilux) to GND (FTDI).
3. Then I connected my FTDI to my PC.
4. Using a small cable I shorted GPIO0 with GND cable I have soldered on the back
5. Plugged the power supply into Arilux (the onboard LED didn't blink)
6. Set the desired configurations in Arduino (DOUT) and hit Upload

But I get this error:

```
Arduino: 1.8.4 (Windows 7), Board: "Generic ESP8266 Module, Serial, 80 MHz, 40MHz, DOUT, 115200, 1M (64K SPIFFS), ck, Disabled, None"
...
warning: espcomm_sync failed
error: espcomm_open failed
error: espcomm_upload_mem failed
error: espcomm_upload_mem failed
```

If I don't short GPIO0 then the onboard LED blinks once when it starts up. I tried shorting GPIO0 with GND that comes with the power cable also. 

Any idea or help would be appreciated!

**Comment by papaiatis** [comment]
I ended up soldering wires to VCC and GND pins of the ESP-12S chip. VCC goes to 3.3V of FTDI.
Please note, that I did not shorted GPIO0 to anywhere!
And restarted Arduino IDE.
This way I could upload the firmware on the device.

**Comment by papaiatis** [comment]
I'm reopening this issue because even though flashing went smoothly after I resolved the wiring issue and I registered the device in Home Assistant the RGB LED strip does not turn on.
The device receives the correct JSON command from the topic `RGB/<id>/json/set` but the LEDs are not turning on.
I enabled JSON by uncommenting `#define JSON`.

What do I do wrong?

Example command and return value:
```
RGB/0091807C/json/set {"state": "ON", "color": {"r": 163, "g": 0, "b": 246}}
RGB/0091807C/json/state {"state":"ON","brightness":255,"white_value":0,"color":{"r":163,"g":0,"b":246}}
```

**Comment by SamZorSec** [comment]
Hi @papaiatis,
Is your module connected to a 12v source? If yes, they may have changed the connections between the ESP and the light strip.

Can you provide me the link where you bought it? I'll maybe order a new version.

Sam

**Comment by papaiatis** [comment]
@mertenats Yes it's connected, otherwise it wouldn't appear through HA discovery and it wouldn't respond to commands. 
I bought it last December on Banggood, so it's not a new product.
I'm afraid I may have fried something while soldering the wires. Not sure how to test it though.
The LED strip is fine, tested with another RF controller.
Any idea would be appreciated.

**Comment by papaiatis** [comment]
I ended up starting everything all over, checked every component, fixed any bad-looking soldering, checked RGB strip, re-flashed firmware, etc... And it magically started working. :+1:
