### ISSUE TITLE
Can't make RF Remote work with LC11

### ISSUE THREAD

**Issue by oglodyte** [mertenats/Arilux_AL-LC0X#38]
Was able to control LC11 with remote before flashing Arilux_AL-LC0X, besides this remote interferes with other RF LED controller, so it sends something. 

But no reaction on pressing remote button with Arilux_AL-LC0X. Not even "ERROR: RF code not defined" in debug messages.

Tried to change ARILUX_RF_PIN to 2 and 16 - no luck.  Out of troubleshooting ideas.  Would appreciate any suggestions. 
Does anyone have  RF remote working with LC11?

**Comment by SamZorSec** [comment]
Hi @oglodyte,
If you have the message `ERROR: RF code not defined`, the codes sent by your remote seem to be different from the codes defined in the sketch and not a problem related to the pin of the RF receiver.
The solution would be to modify the RF codes in the sketch with your own for each button of your remote.

**Comment by oglodyte** [comment]
Thank you @mertenats.  
If I had those ERROR massages, it would give me a clue.   Unfortunately I do not get any error messages as if rcSwitch.available() is never true.  I'm pretty sure RCSwitch is included and complied in  (was giving me errors until I loaded RCSwitch library).  But it does not seem to work for me and I'm not sure how to troubleshoot it further.

**Comment by arendst** [comment]
I'm working on an implementation by my own and discovered the following for Arilux LC11:
- RF input is GPIO15
- RF control is GPIO02

RF input is only enabled if GPIO02 is low (lighting the ESP12-F led).

@mertenats thnx for RCSwitch hint.

**Comment by oglodyte** [comment]
Thank you so much @arendst! 
That does it. Now I have those error messages and should be able to learn the codes.
Who would have guessed about GPIO2?..
BTW, are you adding LC11 and RF support to your Sonoff-Tasmota?  That would be great! I use it for everything but this LC11.  Any chance you also implement JSON mode in Sonoff-Tasmota?

**Comment by oglodyte** [comment]
BTW, here are RF codes for remote that came with my LC11 in case it can help someone.
```
#ifdef RF_REMOTE
#define ARILUX_RF_CODE_KEY_ON           13350401
#define ARILUX_RF_CODE_KEY_TOGGLE       13350402
#define ARILUX_RF_CODE_KEY_OFF          13350403
#define ARILUX_RF_CODE_KEY_SPEED_PLUS   13350404
#define ARILUX_RF_CODE_KEY_MODE_PLUS    13350405
#define ARILUX_RF_CODE_KEY_BRIGHT_PLUS  13350406
#define ARILUX_RF_CODE_KEY_SPEED_MINUS  13350407
#define ARILUX_RF_CODE_KEY_MODE_MINUS   13350408
#define ARILUX_RF_CODE_KEY_BRIGHT_MINUS 13350409
#define ARILUX_RF_CODE_KEY_RED          13350410
#define ARILUX_RF_CODE_KEY_GREEN        13350411
#define ARILUX_RF_CODE_KEY_BLUE         13350412
#define ARILUX_RF_CODE_KEY_ORANGE       13350413
#define ARILUX_RF_CODE_KEY_LTGRN        13350414
#define ARILUX_RF_CODE_KEY_LTBLUE       13350415
#define ARILUX_RF_CODE_KEY_AMBER        13350416
#define ARILUX_RF_CODE_KEY_CYAN         13350417
#define ARILUX_RF_CODE_KEY_PURPLE       13350418
#define ARILUX_RF_CODE_KEY_YELLOW       13350419
#define ARILUX_RF_CODE_KEY_PINK         13350420
#define ARILUX_RF_CODE_KEY_WHITE        13350421
#endif

```
