### ISSUE TITLE
Support for AL-LC01

### ISSUE THREAD

**Issue by papaiatis** [mertenats/Arilux_AL-LC0X#4]
Hi,

I've got an Arilux AL-LC01 controller. Can you please add support for this device as well?

Thank you!

**Comment by SamZorSec** [comment]
Hi,
I don't have an Arilux AL-LC01, but I think it is compatible with the current firmware. Can you try it? Make sure to comment `//#define IR_REMOTE`and `//#define RF_REMOTE`.

Thanks for your feedback,
Sam

**Comment by kilosgreen** [comment]
hi,
 im trying to use your code on a AL-LC01 using Mosquitto but keep running into the same issue 

þINFO: Connecting to: "wifi"
...
INFO: WiFi connected
INFO: IP address: 10.0.0.111

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v3de0c112
~ld

ive tried your suggestion on the comment above but no luck i also tried //#define TLS  seeing that i dont have TSL or SSl set up yet

sorry if this is kinda a dumb question im still very new at HA and mqtt 
thank you

**Comment by SamZorSec** [comment]
You have a strange problem during the initialisation of the module, before/during the establishment of the MQTT connection. One user of the AL-LC01 told me that the firmware is compatible with it. Can you try to flash again the chip/reset it?

**Comment by robbiet480** [comment]
Closing this since it doesn't seem to be a problem with the firmware. Please reopen if the issue still persists.
