### ISSUE TITLE
compile problem IRremote

### ISSUE THREAD

**Issue by rewegit** [mertenats/Arilux_AL-LC0X#42]
First of all, thank you for your program.

With IRremoteESP8266 in Version 2.3.2 I get the following errors:

`Arilux_AL-LC0X:80: error: 'IRrecv' does not name a type
 IRrecv            irRecv(ARILUX_IR_PIN);
 ^
`

And after downgrade to V1.2.0 I get some errors like this:

`/Volumes/myData/Documents/Arduino/libraries/IRremoteESP8266-1.2.0/IRKelvinator.cpp: In member function 'void IRKelvinatorAC::setTemp(uint8_t)':
/Volumes/myData/Documents/Arduino/libraries/IRremoteESP8266-1.2.0/IRKelvinator.cpp:96:41: error: no matching function for call to 'max(unsigned int, uint8_t&)'
     temp = max(KELVINATOR_MIN_TEMP, temp);
                                         ^
`

I hope, you can help me
thx

**Comment by rvt** [comment]
Better late than never... did you add https://github.com/markszabo/IRremoteESP8266 as a library?
