### ISSUE TITLE
Support for RGBW?

### ISSUE THREAD

**Issue by solars** [mertenats/Arilux_AL-LC0X#5]
Hi there,

I noticed there are also RGBW controllers:
http://www.banggood.com/ARILUX-AL-LC02-Super-Mini-LED-WIFI-APP-Controller-Dimmer-for-RGBW-LED-Strip-Light-DC-9-12V-p-1060222.html

would support be possible? :)

**Comment by SamZorSec** [comment]
I've ordered a RGBW lightstrip and I'll try to convert my RGB controller into a RGBW controller (one free pin unused). However, I don't know how to proceed with the firmware to handle the white channel.

- Use the white channel if the RGB value is equal to 255, 255, 255 and turn off the others
- Use the white channel as an independent light (ON/OFF, brightness)
- Try to convert RGB into RGBW and vice versa (Home Assistant supports only RGB with the MQTT component)
